Resources:
  ComputeStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: termassignmentcloud

  ComputeStorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ComputeStorageBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              !Join ["", ["arn:aws:s3:::", !Ref ComputeStorageBucket, "/*"]]
